spring:
  application:
    name: "configserver"
  profiles:
    active: dev
  cloud:
    config:
      server:
        native:
          search-locations: "classpath:/config"
server:
  port: 8071
  
  
